### ISSUE TITLE
ImportError: cannot import name Fatsecret

### ISSUE THREAD

**Issue by DitaAjiPratama** [walexnelson/pyfatsecret#5]
I already Installing with pip:

```
Installing collected packages: urllib3, certifi, chardet, idna, requests, rauth, fatsecret
Successfully installed certifi-2018.11.29 chardet-3.0.4 fatsecret-0.2.3 idna-2.8 rauth-0.7.3 requests-2.21.0 urllib3-1.24.1
```
And Result:

```
Traceback (most recent call last):
  File "fatsecret.py", line 1, in <module>
    from fatsecret import Fatsecret
  File "/home/dita/fatsecret.py", line 1, in <module>
    from fatsecret import Fatsecret
```

**Comment by DitaAjiPratama** [comment]
Aaaagh... Sorry...
I rename my file as fatsecret.py
It makes an error when import fatsecret
